# Makefile.am for dmas subdirectory

lib_LTLIBRARIES = libfap5da.la

libfap5da_la_SOURCES = \
    mproxy.h \
    mrenvadp.h \
    daaproxy.h \
    daaproxy.cpp \
    daaprov.h \
    daaprov.cpp \
    renvadp.h \
    renvadp.cpp \
    envdm.h \
    envdm.cpp \
    nodepx.h \
    nodepx.cpp \
    sysdm.cpp \
    sysdm.h

# Include paths
AM_CPPFLAGS = -I$(top_srcdir)/src
